Name
====

{{ $plugin->dist_name }} - Some clever yet compact description


SYNOPSIS
========

Setup for browsers (see [npm installation notes](http://joose.github.com/Joose/doc/html/Joose/Manual/Installation.html)):

        <!-- Joose ->
        <script type="text/javascript" src="/jsan/Task/Joose/Core.js"></script>    
        
            <!-- JooseX.Namespace.Depended - web-specific files only ->
            <script type="text/javascript" src="/jsan/Task/JooseX/Namespace/Depended/Web.js"></script>

            <!-- or ->
            
            <!-- JooseX.Namespace.Depended - cross-platform bundle ->
            <script type="text/javascript" src="/jsan/Task/JooseX/Namespace/Depended/Auto.js"></script>

        
        <script type="text/javascript">
            use.paths = [ 'lib', '/jsan' ]
        </script>

Setup for NodeJS:

        // this extension is bundled into the following package
        require('task-joose-nodejs')


        // declaring our class
        Class('{{ $plugin->dist_name }}', {
        
        })
        
        // then instantiating it
        var instance = new {{ $plugin->dist_name }}({
        })
        
        // and doing something totally awesome with it :D
        instance.method(param1, param2)
        

If you are reading this file as README from github, you may want to open [this link](http://samuraijack.github.com/{{ $plugin->zilla->name }}) instead. 


DESCRIPTION
===========

`{{ $plugin->dist_name }}` is a stub for Joose-orientied JSAN modules.


ISA
===

None.


DOES
====

None.


TRAITS
======

None.



ATTRIBUTES
==========

### attributeName

> `AttributeType attributeName`

> Attribute description


METHODS
=======

### methodName

> `method signature`

> Method description


EXAMPLES
========

Our class can be used like this:

        // then instantiating it
        var instance = new {{ $plugin->dist_name }}({
        })

and like that:

        // then instantiating it
        var instance = new {{ $plugin->dist_name }}({
        })


GETTING HELP
============

This extension is supported via github issues tracker: <http://github.com/SamuraiJack/{{ $plugin->zilla->name }}/issues>

For general Joose questions you can also visit [#joose](http://webchat.freenode.net/?randomnick=1&channels=joose&prompt=1) 
on irc.freenode.org or mailing list at: <http://groups.google.com/group/joose-js>
 


SEE ALSO
========

Web page of this module: <http://github.com/SamuraiJack/{{ $plugin->zilla->name }}/>

General documentation for Joose: <http://joose.github.com/Joose>


BUGS
====

All complex software has bugs lurking in it, and this module is no exception.

Please report any bugs through the web interface at <http://github.com/SamuraiJack/{{ $plugin->zilla->name }}/issues>



AUTHORS
=======

{{ $OUT .= $_ . "\n\n" foreach (@{$dist->authors})  }}



COPYRIGHT AND LICENSE
=====================

{{ $dist->license->notice }}